---
id: echirolles-tree
name: Échirolles Tree
version: 0.1
description: |
  A customised plugin for Every Door to contribute trees in OpenStreetMap, coming from Every tree plugin by @Binnette
author: SIG Échirolles (eric.vinouze@echirolles.fr), Binnette (binnette@gmail.com) 
icon: every-tree-echirolles-logo.svg
homepage: https://github.com/sig-echirolles/every-tree
source: https://raw.githubusercontent.com/sig-echirolles/every-tree/refs/heads/main/echirolles-tree.edp
experimental: true


presets:
  platanus_×acerifolia:
    name: "Platane Commun"
    terms: ['Platanus ×acerifolia', 'platanus', '×acerifolia']
    area: False
    tags:
      natural: tree
      species: "Platanus ×acerifolia"
    addTags:
      natural: tree
      genus: "Platanus"
      species: "Platanus ×acerifolia"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  pinus_nigra:
    name: "Pin De Salzmann"
    terms: ['Pinus nigra', 'pinus', 'nigra']
    area: False
    tags:
      natural: tree
      species: "Pinus nigra"
    addTags:
      natural: tree
      genus: "Pinus"
      species: "Pinus nigra"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  acer_campestre:
    name: "Érable Champêtre"
    terms: ['Acer campestre', 'acer', 'campestre']
    area: False
    tags:
      natural: tree
      species: "Acer campestre"
    addTags:
      natural: tree
      genus: "Acer"
      species: "Acer campestre"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  magnolia_grandiflora:
    name: "Laurier Tulipier"
    terms: ['Magnolia grandiflora', 'magnolia', 'grandiflora']
    area: False
    tags:
      natural: tree
      species: "Magnolia grandiflora"
    addTags:
      natural: tree
      genus: "Magnolia"
      species: "Magnolia grandiflora"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  acer_platanoides:
    name: "Acer Platanoides"
    terms: ['Acer platanoides', 'acer', 'platanoides']
    area: False
    tags:
      natural: tree
      species: "Acer platanoides"
    addTags:
      natural: tree
      genus: "Acer"
      species: "Acer platanoides"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  prunus_cerasifera:
    name: "Myrobolan"
    terms: ['Prunus cerasifera', 'prunus', 'cerasifera']
    area: False
    tags:
      natural: tree
      species: "Prunus cerasifera"
    addTags:
      natural: tree
      genus: "Prunus"
      species: "Prunus cerasifera"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  pyrus_calleryana:
    name: "Pyrus Calleryana"
    terms: ['Pyrus calleryana', 'pyrus', 'calleryana']
    area: False
    tags:
      natural: tree
      species: "Pyrus calleryana"
    addTags:
      natural: tree
      genus: "Pyrus"
      species: "Pyrus calleryana"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  cupressus_sempervirens:
    name: "Cyprès Commun"
    terms: ['Cupressus sempervirens', 'cupressus', 'sempervirens']
    area: False
    tags:
      natural: tree
      species: "Cupressus sempervirens"
    addTags:
      natural: tree
      genus: "Cupressus"
      species: "Cupressus sempervirens"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  cedrus_libani:
    name: "Cedre Du Liban"
    terms: ['Cedrus libani', 'cedrus', 'libani']
    area: False
    tags:
      natural: tree
      species: "Cedrus libani"
    addTags:
      natural: tree
      genus: "Cedrus"
      species: "Cedrus libani"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  prunus_serrulata:
    name: "Cerisier À Fleurs Japonais"
    terms: ['Prunus serrulata', 'prunus', 'serrulata']
    area: False
    tags:
      natural: tree
      species: "Prunus serrulata"
    addTags:
      natural: tree
      genus: "Prunus"
      species: "Prunus serrulata"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  cedrus_atlantica:
    name: "Cèdre Bleu De L'Atlas"
    terms: ['Cedrus atlantica', 'cedrus', 'atlantica']
    area: False
    tags:
      natural: tree
      species: "Cedrus atlantica"
    addTags:
      natural: tree
      genus: "Cedrus"
      species: "Cedrus atlantica"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  pinus_sylvestris:
    name: "Pin D'Écosse"
    terms: ['Pinus sylvestris', 'pinus', 'sylvestris']
    area: False
    tags:
      natural: tree
      species: "Pinus sylvestris"
    addTags:
      natural: tree
      genus: "Pinus"
      species: "Pinus sylvestris"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  quercus_ilex:
    name: "Chêne Vert"
    terms: ['Quercus ilex', 'quercus', 'ilex']
    area: False
    tags:
      natural: tree
      species: "Quercus ilex"
    addTags:
      natural: tree
      genus: "Quercus"
      species: "Quercus ilex"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  tilia_cordata:
    name: "Tilia Sylvestris"
    terms: ['Tilia cordata', 'tilia', 'cordata']
    area: False
    tags:
      natural: tree
      species: "Tilia cordata"
    addTags:
      natural: tree
      genus: "Tilia"
      species: "Tilia cordata"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  populus_nigra:
    name: "Peuplier Noir"
    terms: ['Populus nigra', 'populus', 'nigra']
    area: False
    tags:
      natural: tree
      species: "Populus nigra"
    addTags:
      natural: tree
      genus: "Populus"
      species: "Populus nigra"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  tilia_tomentosa:
    name: "Tilleul Argente"
    terms: ['Tilia tomentosa', 'tilia', 'tomentosa']
    area: False
    tags:
      natural: tree
      species: "Tilia tomentosa"
    addTags:
      natural: tree
      genus: "Tilia"
      species: "Tilia tomentosa"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  sophora_japonica:
    name: "Sophora Du Japon"
    terms: ['Sophora japonica', 'sophora', 'japonica']
    area: False
    tags:
      natural: tree
      species: "Sophora japonica"
    addTags:
      natural: tree
      genus: "Sophora"
      species: "Sophora japonica"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  lagerstroemia_indica:
    name: "Lilas D'Été"
    terms: ['Lagerstroemia indica', 'lagerstroemia', 'indica']
    area: False
    tags:
      natural: tree
      species: "Lagerstroemia indica"
    addTags:
      natural: tree
      genus: "Lagerstroemia"
      species: "Lagerstroemia indica"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  arbutus_unedo:
    name: "Arbouse"
    terms: ['Arbutus unedo', 'arbutus', 'unedo']
    area: False
    tags:
      natural: tree
      species: "Arbutus unedo"
    addTags:
      natural: tree
      genus: "Arbutus"
      species: "Arbutus unedo"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  prunus_mahaleb:
    name: "Bois De Sainte Lucie"
    terms: ['Prunus mahaleb', 'prunus', 'mahaleb']
    area: False
    tags:
      natural: tree
      species: "Prunus mahaleb"
    addTags:
      natural: tree
      genus: "Prunus"
      species: "Prunus mahaleb"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  carpinus_betulus:
    name: "Carpinus Betulus"
    terms: ['Carpinus betulus', 'carpinus', 'betulus']
    area: False
    tags:
      natural: tree
      species: "Carpinus betulus"
    addTags:
      natural: tree
      genus: "Carpinus"
      species: "Carpinus betulus"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  cercis_siliquastrum:
    name: "Arbre De Judee"
    terms: ['Cercis siliquastrum', 'cercis', 'siliquastrum']
    area: False
    tags:
      natural: tree
      species: "Cercis siliquastrum"
    addTags:
      natural: tree
      genus: "Cercis"
      species: "Cercis siliquastrum"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  robinia_pseudoacacia:
    name: "Faux Acacia"
    terms: ['Robinia pseudoacacia', 'robinia', 'pseudoacacia']
    area: False
    tags:
      natural: tree
      species: "Robinia pseudoacacia"
    addTags:
      natural: tree
      genus: "Robinia"
      species: "Robinia pseudoacacia"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  acer_monspessulanum:
    name: "Acer Monspessulanum"
    terms: ['Acer monspessulanum', 'acer', 'monspessulanum']
    area: False
    tags:
      natural: tree
      species: "Acer monspessulanum"
    addTags:
      natural: tree
      genus: "Acer"
      species: "Acer monspessulanum"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  gleditsia_triacanthos:
    name: "Févier"
    terms: ['Gleditsia triacanthos', 'gleditsia', 'triacanthos']
    area: False
    tags:
      natural: tree
      species: "Gleditsia triacanthos"
    addTags:
      natural: tree
      genus: "Gleditsia"
      species: "Gleditsia triacanthos"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  cupressus_arizonica:
    name: "Cyprès Bleu"
    terms: ['Cupressus arizonica', 'cupressus', 'arizonica']
    area: False
    tags:
      natural: tree
      species: "Cupressus arizonica"
    addTags:
      natural: tree
      genus: "Cupressus"
      species: "Cupressus arizonica"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  acer_saccharinum:
    name: "Acer Saccharinum"
    terms: ['Acer saccharinum', 'acer', 'saccharinum']
    area: False
    tags:
      natural: tree
      species: "Acer saccharinum"
    addTags:
      natural: tree
      genus: "Acer"
      species: "Acer saccharinum"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  juniperus_scopulorum:
    name: "Genevrier De Virginie"
    terms: ['Juniperus scopulorum', 'juniperus', 'scopulorum']
    area: False
    tags:
      natural: tree
      species: "Juniperus scopulorum"
    addTags:
      natural: tree
      genus: "Juniperus"
      species: "Juniperus scopulorum"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  chionanthus_retusus:
    name: "Arbre À Franges De Chine"
    terms: ['Chionanthus retusus', 'chionanthus', 'retusus']
    area: False
    tags:
      natural: tree
      species: "Chionanthus retusus"
    addTags:
      natural: tree
      genus: "Chionanthus"
      species: "Chionanthus retusus"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"
  pyrus_pyraster:
    name: "Poirier Sauvage"
    terms: ['Pyrus pyraster', 'pyrus', 'pyraster']
    area: False
    tags:
      natural: tree
      species: "Pyrus pyraster"
    addTags:
      natural: tree
      genus: "Pyrus"
      species: "Pyrus pyraster"
    fields:
      - species_i
      - height
      - circumference
      - leaf_type
      - leaf_cycle
      - "@natural/tree"

kinds:
  tree:
    matcher:
      natural:
        only: [tree]

fields:
  access_i:
    type: combo
    key: access
    label: Access
    options:
      - "yes"
      - "private"
      - "permissive"
    labels:
      - "Public"
      - "Private"
      - "Permissive"
  age_i:
    type: combo
    key: age
    label: Age
    options:
      - "young"
      - "semi-mature"
      - "mature"
    labels:
      - "Young"
      - "Semi-mature"
      - "Mature"
  species_i:
    type: combo
    customValues: true
    key: species
    label: Species
    options:
      - "Platanus ×acerifolia"
      - "Pinus nigra"
      - "Acer campestre"
      - "Magnolia grandiflora"
      - "Acer platanoides"
      - "Prunus cerasifera"
      - "Pyrus calleryana"
      - "Cupressus sempervirens"
      - "Cedrus libani"
      - "Prunus serrulata"
      - "Cedrus atlantica"
      - "Pinus sylvestris"
      - "Quercus ilex"
      - "Tilia cordata"
      - "Populus nigra"
      - "Tilia tomentosa"
      - "Sophora japonica"
      - "Lagerstroemia indica"
      - "Arbutus unedo"
      - "Prunus mahaleb"
      - "Carpinus betulus"
      - "Cercis siliquastrum"
      - "Robinia pseudoacacia"
      - "Acer monspessulanum"
      - "Gleditsia triacanthos"
      - "Cupressus arizonica"
      - "Acer saccharinum"
      - "Juniperus scopulorum"
      - "Chionanthus retusus"
      - "Pyrus pyraster"
    labels:
      - "Platanus ×acerifolia"
      - "Pinus nigra"
      - "Acer campestre"
      - "Magnolia grandiflora"
      - "Acer platanoides"
      - "Prunus cerasifera"
      - "Pyrus calleryana"
      - "Cupressus sempervirens"
      - "Cedrus libani"
      - "Prunus serrulata"
      - "Cedrus atlantica"
      - "Pinus sylvestris"
      - "Quercus ilex"
      - "Tilia cordata"
      - "Populus nigra"
      - "Tilia tomentosa"
      - "Sophora japonica"
      - "Lagerstroemia indica"
      - "Arbutus unedo"
      - "Prunus mahaleb"
      - "Carpinus betulus"
      - "Cercis siliquastrum"
      - "Robinia pseudoacacia"
      - "Acer monspessulanum"
      - "Gleditsia triacanthos"
      - "Cupressus arizonica"
      - "Acer saccharinum"
      - "Juniperus scopulorum"
      - "Chionanthus retusus"
      - "Pyrus pyraster"

modes:
  tree:
    type: entrances
    icon: tree.svg
    name: Tree
    kinds: [fig, tree]
    markers:
      fig:
        icon: fig.svg
      tree:
        requiredKeys: [species]
        icon: tree-ok.svg
        iconPartial: tree-ko.svg
    primary:
      onMainKey: false
      preset: natural/tree
      icon: tree.svg
      tooltip: Tree
      adjustZoom: 0.7
      kind: tree
      fields:
        - species_i
        - height
        - circumference
        - leaf_type
        - leaf_cycle
        # - access_i
        # - age_i
        # - description